<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sitemap [
  <!ELEMENT urlset (url+)>
  <!ELEMENT url (loc, lastmod, changefreq, priority?)>
  <!ELEMENT loc (#PCDATA)>
  <!ELEMENT lastmod (#PCDATA)>
  <!ELEMENT changefreq (#PCDATA)>
  <!ELEMENT priority (#PCDATA)>
]>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  
    
    <url>
      <loc>https://xmuplus.github.io/current-issue/</loc>
      
        <lastmod>2019-03-30T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/epub-mobi/</loc>
      
        <lastmod>2019-03-29T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/03/22/Mar-22nd-2019/</loc>
      
        <lastmod>2019-03-22T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/03/16/Mar-16th-2019/</loc>
      
        <lastmod>2019-03-16T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/03/09/Mar-09th-2019/</loc>
      
        <lastmod>2019-03-09T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/03/02/Mar-02nd-2019/</loc>
      
        <lastmod>2019-03-02T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/02/23/Feb-23rd-2019/</loc>
      
        <lastmod>2019-02-23T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/02/16/Feb-16th-2019/</loc>
      
        <lastmod>2019-02-16T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/02/09/Feb-09th-2019/</loc>
      
        <lastmod>2019-02-09T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/02/02/Feb-02nd-2019/</loc>
      
        <lastmod>2019-02-02T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/01/26/Jan-26th-2019/</loc>
      
        <lastmod>2019-01-26T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/01/19/Jan-19th-2019/</loc>
      
        <lastmod>2019-01-19T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/01/12/Jan-12th-2019/</loc>
      
        <lastmod>2019-01-12T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2019/01/05/Jan-05th-2019/</loc>
      
        <lastmod>2019-01-05T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/12/22/Dec-22nd-2018/</loc>
      
        <lastmod>2018-12-22T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/12/15/Dec-15th-2018/</loc>
      
        <lastmod>2018-12-15T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/12/08/Dec-08th-2018/</loc>
      
        <lastmod>2018-12-08T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/12/01/Dec-01st-2018/</loc>
      
        <lastmod>2018-12-01T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/11/24/Nov-24th-2018/</loc>
      
        <lastmod>2018-11-24T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/11/17/Nov-17th-2018/</loc>
      
        <lastmod>2018-11-17T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/11/10/Nov-10th-2018/</loc>
      
        <lastmod>2018-11-10T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/11/03/Nov-03rd-2018/</loc>
      
        <lastmod>2018-11-03T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/10/27/Oct-27th-2018/</loc>
      
        <lastmod>2018-10-27T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/10/20/Oct-20th-2018/</loc>
      
        <lastmod>2018-10-20T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/10/13/Oct-13th-2018/</loc>
      
        <lastmod>2018-10-13T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/10/06/Oct-06th-2018/</loc>
      
        <lastmod>2018-10-06T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/09/29/Sep-29th-2018/</loc>
      
        <lastmod>2018-09-29T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/09/22/Sep-22nd-2018/</loc>
      
        <lastmod>2018-09-22T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/09/15/Sep-15th-2018/</loc>
      
        <lastmod>2018-09-15T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/09/08/Sep-08th-2018/</loc>
      
        <lastmod>2018-09-08T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/09/01/Sep-01st-2018/</loc>
      
        <lastmod>2018-09-01T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/08/25/Aug-25h-2018/</loc>
      
        <lastmod>2018-08-25T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/08/18/Aug-18th-2018/</loc>
      
        <lastmod>2018-08-18T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/08/11/Aug-11th-2018/</loc>
      
        <lastmod>2018-08-11T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/08/04/Aug-04th-2018/</loc>
      
        <lastmod>2018-08-04T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/07/28/July-28th-2018/</loc>
      
        <lastmod>2018-07-28T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/07/21/July-21st-2018/</loc>
      
        <lastmod>2018-07-21T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/07/14/July-14th-2018/</loc>
      
        <lastmod>2018-07-14T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/07/07/July-07th-2018/</loc>
      
        <lastmod>2018-07-07T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/06/30/June-30th-2018/</loc>
      
        <lastmod>2018-06-30T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/06/23/June-23rd-2018/</loc>
      
        <lastmod>2018-06-23T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/06/16/June-16th-2018/</loc>
      
        <lastmod>2018-06-16T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/06/09/June-09th-2018/</loc>
      
        <lastmod>2018-06-09T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/06/02/June-02nd-2018/</loc>
      
        <lastmod>2018-06-02T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/05/26/May-26th-2018/</loc>
      
        <lastmod>2018-05-26T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/05/19/May-19th-2018/</loc>
      
        <lastmod>2018-05-19T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/05/12/May-12th-2018/</loc>
      
        <lastmod>2018-05-12T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/05/05/May-05th-2018/</loc>
      
        <lastmod>2018-05-05T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/04/28/Apr-28th-2018/</loc>
      
        <lastmod>2018-04-28T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/04/21/Apr-21st-2018/</loc>
      
        <lastmod>2018-04-21T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/04/14/Apr-14th-2018/</loc>
      
        <lastmod>2018-04-14T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/04/07/Apr-07th-2018/</loc>
      
        <lastmod>2018-04-07T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/03/31/Apr-31st-2018/</loc>
      
        <lastmod>2018-03-31T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/03/24/Mar-24th-2018/</loc>
      
        <lastmod>2018-03-24T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/03/17/Mar-17th-2018/</loc>
      
        <lastmod>2018-03-17T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/03/10/Mar-10th-2018/</loc>
      
        <lastmod>2018-03-10T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/03/03/Mar-03rd-2018/</loc>
      
        <lastmod>2018-03-03T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/02/24/Feb-24th-2018/</loc>
      
        <lastmod>2018-02-24T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/02/17/Feb-17th-2018/</loc>
      
        <lastmod>2018-02-17T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/02/10/Feb-10th-2018/</loc>
      
        <lastmod>2018-02-10T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/02/03/Feb-03rd-2018/</loc>
      
        <lastmod>2018-02-03T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/01/27/Jan-27th-2018/</loc>
      
        <lastmod>2018-01-27T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/01/20/Jan-20th-2018/</loc>
      
        <lastmod>2018-01-20T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/01/13/Jan-13th-2018/</loc>
      
        <lastmod>2018-01-13T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2018/01/06/Jan-06th-2018/</loc>
      
        <lastmod>2018-01-06T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/12/23/Dec-23rd-2017/</loc>
      
        <lastmod>2017-12-23T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/12/16/Dec-16th-2017/</loc>
      
        <lastmod>2017-12-16T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/12/09/Dec-09th-2017/</loc>
      
        <lastmod>2017-12-09T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/12/02/Dec-02nd-2017/</loc>
      
        <lastmod>2017-12-02T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/11/25/special_report-Nov-25th-2017/</loc>
      
        <lastmod>2017-11-25T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/11/25/Nov-25th-2017/</loc>
      
        <lastmod>2017-11-25T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/11/18/Nov-18th-2017/</loc>
      
        <lastmod>2017-11-18T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/11/13/TIME-Nov-13th-2017/</loc>
      
        <lastmod>2017-11-13T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/11/11/Nov-11th-2017/</loc>
      
        <lastmod>2017-11-11T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/11/04/Nov-04th-2017/</loc>
      
        <lastmod>2017-11-04T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/10/28/Oct-28th-2017/</loc>
      
        <lastmod>2017-10-28T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/10/21/Oct-21st-2017/</loc>
      
        <lastmod>2017-10-21T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/10/14/Oct-14th-2017/</loc>
      
        <lastmod>2017-10-14T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/10/07/Oct-07th-2017/</loc>
      
        <lastmod>2017-10-07T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/09/30/Sep-30th-2017/</loc>
      
        <lastmod>2017-09-30T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/09/23/Sep-23rd-2017/</loc>
      
        <lastmod>2017-09-23T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/09/16/Sep-16th-2017/</loc>
      
        <lastmod>2017-09-16T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/09/09/Sep-09th-2017/</loc>
      
        <lastmod>2017-09-09T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/09/02/Sep-02nd-2017/</loc>
      
        <lastmod>2017-09-02T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/08/26/Aug-26th-2017/</loc>
      
        <lastmod>2017-08-26T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/08/19/Aug-19th-2017/</loc>
      
        <lastmod>2017-08-19T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/08/12/Aug-12th-2017/</loc>
      
        <lastmod>2017-08-12T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/08/05/Aug-05th-2017/</loc>
      
        <lastmod>2017-08-05T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/07/29/Jul-29th-2017/</loc>
      
        <lastmod>2017-07-29T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/07/22/Jul-22nd-2017/</loc>
      
        <lastmod>2017-07-22T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/07/15/Jul-15th-2017/</loc>
      
        <lastmod>2017-07-15T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/07/08/Jul-08th-2017/</loc>
      
        <lastmod>2017-07-08T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/07/01/Jul-01st-2017/</loc>
      
        <lastmod>2017-07-01T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/06/24/Jun-24th-2017/</loc>
      
        <lastmod>2017-06-24T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/06/17/Jun-17th-2017/</loc>
      
        <lastmod>2017-06-17T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/06/10/Jun-10th-2017/</loc>
      
        <lastmod>2017-06-10T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/06/03/Jun-03rd-2017/</loc>
      
        <lastmod>2017-06-03T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/05/27/May-27th-2017/</loc>
      
        <lastmod>2017-05-27T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/05/20/May-20th-2017/</loc>
      
        <lastmod>2017-05-20T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/05/18/special_report-May-20th-2017/</loc>
      
        <lastmod>2017-05-18T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/05/17/Scientific_American_May_2017/</loc>
      
        <lastmod>2017-05-17T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/05/13/May-13th-2017/</loc>
      
        <lastmod>2017-05-13T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/05/06/May-06th-2017/</loc>
      
        <lastmod>2017-05-06T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/05/05/special_report-May-06th-2017/</loc>
      
        <lastmod>2017-05-05T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/05/04/Newsweek-May-12th-2017/</loc>
      
        <lastmod>2017-05-04T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/04/29/Apr-29th-2017/</loc>
      
        <lastmod>2017-04-29T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/04/22/Apr-22nd-2017/</loc>
      
        <lastmod>2017-04-22T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>
      <loc>https://xmuplus.github.io/2017/04/15/Apr-15th-2017/</loc>
      
        <lastmod>2017-04-15T00:00:00+08:00</lastmod>
      
      
        <changefreq>monthly</changefreq>
      
      
        <priority>0.5</priority>
      
    </url>
    
  
    
    <url>